// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojfhzceccazgenjalhbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qZmh6Y2VjY2F6Z2VuamFsaGJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NDkzMDAsImV4cCI6MjA2MzEyNTMwMH0.GQqo6OKGVLEWKgJFzCsa3tKet5ZvjfPXtAXwX9QA5uM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);